# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        args: [--line-length, "300"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--line-length, "300"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--enforce-all]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length, "300", --ignore, "E203,E302,W503"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --show-error-codes]
        additional_dependencies: [types-aiofiles, types-requests, types-PyYAML, types-redis, types-setuptools]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: /test_.*\.
      - id: bandit
        name: bandit (on unit tests)
        files: /test_.*\.
        args: [-s, B101]  # Ignore assert_used on unit tests.
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.4.0
    hooks:
      - id: pip-compile
        entry: pip-compile-wrapper/pip-compile-wrapper.py
        always_run: true
  - repo: https://github.com/MeghComputing/pre-commit-hooks
    rev: v2022.1
    hooks:
      - id: copyrighter
        args: [--fix]
