name: Linting

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.PRE_COMMIT_AGENT_APP_ID }}
        private_key: ${{ secrets.PRE_COMMIT_AGENT_PRIVATE_KEY }}
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ' '
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: pre-commit
      uses: pre-commit/action@v2.0.3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        extra_args: --files ${{ steps.file_changes.outputs.files_added }} ${{ steps.file_changes.outputs.files_modified }}
