name: Unit Tests

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pytest:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install system dependencies
      run: |
        pip install --upgrade pip
        pip install '.[test]'
    - name: Run unit tests
      run: pytest --junitxml=pytest.xml
    - name: Publish unit test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: pytest.xml
